### ISSUE TITLE
Setting up FIdelity framework

### ISSUE THREAD

**Issue by abhishektyaagi** [silvaurus/FIdelityFramework#1]
Hi,
Thank you for sharing the code for FIdelity with us. 

I was wondering if it is possible for you to share the exact requirements for running the framework?

From the README it is clear that TF 1.12 is required, but while installing TF and tf_slim I am encountering a few errors. If you can let us know the exact tf_slim and python version, to start with, I think it would be really helpful

**Comment by silvaurus** [comment]
Hello! 

The python version I used was 3.6.12. 
For slim, when you download it from GitHub, you can try switching the branch to r1.12.0.

Best Regards,

**Comment by abhishektyaagi** [comment]
Thank you for letting us know!
